FROM node:20-alpine

#set working direclty
WORKDIR /app

#copy package.json file
COPY package*.json ./

#install dependency
RUN npm install

#copy source code
COPY . . 

#expose code
EXPOSE 5000

#start the applycation
CMD ["npm" ,"start"]
